version: '0.0.{build}'

init:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

configuration:
  - Debug
  - Release

environment:
  global:
    PYTHON: "C:\\Python36"

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    arch: x86_64
    platform: x64
    visual_studio: Visual Studio 16 2019
    compiler_toolset: v142
    gtest: 1.10.0
    OpenSSL: 1.1.1g

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: x86
    platform: Win32
    visual_studio: Visual Studio 15 2017
    compiler_toolset: v141
    gtest: 1.7.0
    OpenSSL: 1.0.2n

install:
  - "SET PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%"
  - pip.exe install conan
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

before_build:
  - md build
  - cd build
  - conan install .. -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST% -o openssl=%OPENSSL%
  - cmake .. -G "%VISUAL_STUDIO%" -A %PLATFORM%
  
build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\RESTAPICore.sln

after_build:
  - conan export-pkg ../conanfile.py RESTAPICore/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST% -o openssl=%OPENSSL%
  - conan test ../test_package/conanfile.py RESTAPICore/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST% -o openssl=%OPENSSL%
  - conan export-pkg ../test/RESTAPICoreTestUtilities/conanfile.py RESTAPICoreTestUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST% -o openssl=%OPENSSL%
  - conan test ../test/RESTAPICoreTestUtilities/test_package/conanfile.py RESTAPICoreTestUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST% -o openssl=%OPENSSL%

test_script:
  - ps: cd bin
  - ps: cd $env:CONFIGURATION
  - RESTAPICoreTest.exe --gtest_output=xml:RESTAPICoreTest.xml

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\RESTAPICoreTest.xml))

artifacts:
  - path: 'build\lib\%CONFIGURATION%\RESTAPICore.lib'
    name: RESTAPICore.lib
  - path: 'build\lib\%CONFIGURATION%\RESTAPICoreTestUtilities.lib'
    name: RESTAPICoreTestUtilities.lib

deploy_script:
  - ps: >- 
      if($env:appveyor_repo_tag -eq 'True') {
        conan upload RESTAPICore/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
        conan upload RESTAPICoreTestUtilities/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
      } else {
        echo "Not uploading because this is not a tag build"
      }
